export const AuditType = {
  pipeline: "pipeline",
  access: "access",
  monitor: "monitor",
  notification: "notification",
  openKey: "openKey",
  cname: "cname",
  user: "user",
  role: "role",
  permission: "permission",
  project: "project",
  settings: "settings",
  domain: "domain",
  dnsPersist: "dnsPersist",
  certTemplate: "certTemplate",
  pipelineGroup: "pipelineGroup",
  subDomain: "subDomain",
  template: "template",
  mine: "mine",
  login: "login",
  addon: "addon",
  enterprise: "enterprise",
  plugin: "plugin",
  siteIp: "siteIp",
  jobHistory: "jobHistory",
  account: "account",
  plus: "plus",
} as const;

export const AuditTypeMap = {
  pipeline: "流水线",
  access: "授权管理",
  monitor: "站点监控",
  notification: "通知设置",
  openKey: "API密钥",
  cname: "CNAME记录",
  user: "用户管理",
  role: "角色管理",
  permission: "权限管理",
  project: "项目管理",
  settings: "系统设置",
  domain: "域名管理",
  dnsPersist: "持久验证记录",
  certTemplate: "证书参数模版",
  pipelineGroup: "流水线分组",
  subDomain: "子域名托管",
  template: "流水线模版",
  mine: "个人设置",
  login: "登录日志",
  addon: "扩展插件",
  enterprise: "企业管理",
  plugin: "插件管理",
  siteIp: "站点IP",
  jobHistory: "监控历史",
  account: "账号管理",
  plus: "Plus许可",
} as const;

export const AuditAction = {
  add: "add",
  update: "update",
  delete: "delete",
  execute: "execute",
  cancel: "cancel",
  batchDelete: "batchDelete",
  batchUpdate: "batchUpdate",
  disable: "disable",
  import: "import",
  bind: "bind",
  unbind: "unbind",
  register: "register",
  login: "login",
  resetStatus: "resetStatus",
  setDefault: "setDefault",
  save: "save",
  trigger: "trigger",
  active: "active",
} as const;

export const AuditActionMap = {
  add: "新增",
  update: "修改",
  delete: "删除",
  execute: "执行",
  cancel: "取消",
  batchDelete: "批量删除",
  batchUpdate: "批量修改",
  disable: "禁用",
  import: "导入",
  bind: "绑定",
  unbind: "解绑",
  register: "注册",
  login: "登录",
  resetStatus: "重置状态",
  setDefault: "设置默认",
  save: "保存",
  trigger: "触发",
  active: "激活",
} as const;

export const AuditTypeColorMap: Record<string, string> = {
  pipeline: "blue",
  access: "orange",
  monitor: "green",
  notification: "purple",
  openKey: "red",
  cname: "cyan",
  user: "cyan",
  role: "geekblue",
  permission: "lime",
  project: "gold",
  settings: "magenta",
  domain: "blue",
  dnsPersist: "purple",
  certTemplate: "orange",
  pipelineGroup: "cyan",
  subDomain: "geekblue",
  template: "blue",
  mine: "default",
  login: "red",
  addon: "orange",
  enterprise: "gold",
  plugin: "magenta",
  siteIp: "green",
  jobHistory: "default",
  account: "geekblue",
  plus: "volcano",
};

export const AuditActionColorMap: Record<string, string> = {
  add: "green",
  update: "blue",
  delete: "red",
  execute: "orange",
  cancel: "default",
  batchDelete: "volcano",
  batchUpdate: "purple",
  disable: "default",
  import: "cyan",
  bind: "green",
  unbind: "red",
  register: "green",
  login: "blue",
  resetStatus: "orange",
  setDefault: "cyan",
  save: "purple",
  trigger: "orange",
  active: "green",
};

export function buildAuditTypeDict() {
  return Object.entries(AuditTypeMap).map(([value, label]) => ({
    value,
    label,
    color: AuditTypeColorMap[value],
  }));
}

export function buildAuditActionDict() {
  return Object.entries(AuditActionMap).map(([value, label]) => ({
    value,
    label,
    color: AuditActionColorMap[value],
  }));
}
