name: publish-github
on:
  push:
    branches: ['v2-dev']
    paths:
      - 'trigger/publish.trigger'
  workflow_run:
    workflows: ['build-image-for-release']
    types:
      - completed
  workflow_dispatch: # 添加手动触发
#  schedule:
#    - # 国际时间 19:17 执行，北京时间3:17  ↙↙↙ 改成你想要每天自动执行的时间
#    - cron: '17 19 * * *'
permissions:
  contents: read
  packages: write

jobs:
  publish-github:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          ref: 'v2-dev'

      - name: publish_to_github
        id: publish_to_github
        run: |
          export GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
          rm -rf ./pnpm*.yaml
          npm install -g pnpm@10.33.4
          pnpm install
          npm run publish_to_github
        working-directory: ./
